import { Link, useLocation } from "react-router-dom";

function ResultPage() {
  const location = useLocation();
  const statePrice =
    typeof location.state?.price === "number" ? location.state.price : null;

  const savedPrice = Number(sessionStorage.getItem("predictedPrice"));
  const price =
    statePrice !== null ? statePrice : Number.isFinite(savedPrice) ? savedPrice : null;

  if (price === null) {
    return (
      <main className="page centered-page">
        <div className="result-card">
          <div className="result-icon">?</div>
          <h1>No prediction yet</h1>
          <p>Submit the property form first to see a predicted price.</p>
          <Link className="primary-link" to="/">
            Back to prediction form
          </Link>
        </div>
      </main>
    );
  }

  return (
    <main className="page centered-page">
      <div className="result-card">
        <div className="result-icon">₹</div>
        <p className="result-label">Estimated property value</p>
        <h1>
          ₹{" "}
          {price.toLocaleString("en-IN", {
            maximumFractionDigits: 0,
          })}
        </h1>
        <p className="result-note">
          This estimate is generated by the trained house-price prediction
          pipeline.
        </p>

        <div className="result-actions">
          <Link className="primary-link" to="/">
            Predict another property
          </Link>
        </div>
      </div>
    </main>
  );
}

export default ResultPage;
